services:
  - type: web
    name: backend
    env: node
    buildCommand: cd apps/backend-nest && yarn install && yarn add @nestjs/cli && yarn run build
    startCommand: cd apps/backend-nest && yarn run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_CONNECTION_URI
        sync: false
      - key: DB_NAME
        sync: false

    - type: web
      name: frontend
      env: node
      buildCommand: cd apps/frontend-next && yarn install && yarn build
      startCommand: cd apps/frontend-next && yarn start
      envVars:
        - key: NODE_ENV
          value: production
        - key: NEXT_PUBLIC_BACKEND_URL
          fromService:
            type: web
            name: backend
            envVarKey: RENDER_EXTERNAL_HOSTNAME
