import type { Metadata } from "next";
import "./globals.css";
import "@fontsource/poppins";
import NavBottom from "@/components/NavBottom";
import NavTop from "@/components/NavTop";
import { AlephiumWalletProvider } from "@alephium/web3-react";
import themeConfig from "./theme";
import { ThemeProvider } from "@mui/material";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container">
        <AlephiumWalletProvider network="mainnet">
          <ThemeProvider theme={themeConfig}>
            <NavTop />
            {children}
            <NavBottom />
          </ThemeProvider>
        </AlephiumWalletProvider>
      </body>
    </html>
  );
}
